### ISSUE TITLE
integrate with the bug database

### ISSUE THREAD

**Issue by wasowski** [gavanderhoorn/rosin_bug_hunt_l3#4]
I think this is slowly becoming part of our bug database. We should move it there. 

And while we are doing it we should probably move the data to an open repo, independent of the paper (so that this is a proper code repo). 

We also need to discuss how to maximize the reuse of the scripts between bugs.

**Comment by gavanderhoorn** [comment]
Can you clarify what you mean exactly by *this*? The workflow described in #2 should really be transformed into a tool. I'd rather keep that tool in a separate repository.

The other things in this repository are mostly some demo `Dockerfile`s and some utility scripts. I'm fine with moving those anywhere, but they were really just meant to demonstrate some principles and prototype some approaches.

**Comment by wasowski** [comment]
well. There is a bunch of things here:
1. #2 could indeed become a tool, but for the time being, while you don't have time to do this. I don't mind running this manually for the bugs I am studying.  Even if the tool appears at some point, I likely don't need to change my rosinstall files. #2 indeed should stay as a separate thing.
2. The things in the source code repository there are becoming part of data in some way or another (Docker files, entrypoints)
3. The build.sh file can grow into a bigger tool as well, and then it should stay here (and the Docker files etc are likely staying here as the static part of that tool)

So perhaps no moving is necessary. It is just when I add the Dockerfile to the bugs, I need to be able to make changes to it (or ideally to split it into a common and specialized part) and we need to evolve these docker files in the database, not so much here? Unless we find out a process of keeping them out of the data, until an official release when we freeze them.  I am  a bit confused how to handle that, and when this becomes 177 bugs, we have a maintainance problem, so I am trying to streamline this somehow in my head.

**Comment by gavanderhoorn** [comment]
>  It is just when I add the Dockerfile to the bugs, I need to be able to make changes to it (or ideally to split it into a common and specialized part) and we need to evolve these docker files in the database, not so much here?

I completely agree that this repository is not the place to store the `Dockerfile`s. They should go into the other repository.

Again: I just created this repository to host some things I created for you guys to see whether the approaches would work for what we had in mind. It's really just a temporary sandbox.

**Comment by wasowski** [comment]
I understand. I am not debating your choices. I created this issue, so that we can discuss, how to organize this.

**Comment by gavanderhoorn** [comment]
With the publication of [rosinstall_generator_time_machine](https://github.com/gavanderhoorn/rosinstall_generator_time_machine) I think we've implemented the main suggestion in this issue.

The rest of the info / data / files / infrastructure can now be found in [robust-rosin/robust](https://github.com/robust-rosin/robust), so closing.
