### ISSUE TITLE
Remove temporaries

### ISSUE THREAD

**Issue by wasowski** [gavanderhoorn/rosin_bug_hunt_l3#5]
I am wondering about this line 

```
# remove temporaries
RUN rm -rf /ros_ws/build_isolated /ros_ws/devel_isolated
```
Don't we need them to run tests and demonstrate failure? (I stil don't know ROS enough to understand what is in devel and in build).

**Comment by gavanderhoorn** [comment]
That is actually one of the questions in the [TODO section](https://github.com/gavanderhoorn/rosin_bug_hunt_l3/blob/l3_time_machine_tf2_ros/README.md#todo) of the readme.

> Don't we need them to run tests and demonstrate failure?

Whether we need them for tests depends on whether we're going to be running the "ros tests" (whatever that includes), or whether we're just going to run some binary or script that we supply ourselves.

For anything that depends on `rostest` and its integration with various other frameworks, the `build` and `devel` space are probably needed, yes.

**Comment by wasowski** [comment]
This could be the reason why I am seeing strange errors trying to run these tests.  I am initially trying to see whether I cannot use rostest as the way to reproduce bugs.  Although this might not be not so smart, because ros-test is rather idiosyncratic, and perhaps a more classic ros-independent way should be used.  Not sure here.

**Comment by wasowski** [comment]
@ChrisTimperley

**Comment by gavanderhoorn** [comment]
You could comment the line to build an image with the build and devel spaces included. That should fix that.

This is one of the reasons why I initially left the catkin workspace out of the image entirely in my first prototypes. Users of the images can then set it up in their home dirs somewhere and do whatever.

The advantage is that we don't have such bloated images and that users can easily access the source files of the packages under test, the test results and other artefacts in the workspace, but a disadvantage is that every user will have to build the workspace again.

**Comment by wasowski** [comment]
Well, this will sort it out for me, but we probably need a general decision on this.  It is likely better that the Dockerfile-s don't have inessential differences between them for individual bugs. 

A related question is the build type which is set up to be : `-DCMAKE_BUILD_TYPE=Release`. Again, I don't really know what is the impact of this decision in ROS.  Do the tests work as expected in a release build? Is this just about the debugging info, or is there more to this?

**Comment by gavanderhoorn** [comment]
You're asking the right questions, as I also asked those (in the `TODO` section of the `readme`).

`CMAKE_BUILD_TYPE` controls what sort of compiler flags are passed to the compiler. See [CMAKE_BUILD_TYPE](https://cmake.org/cmake/help/v3.0/variable/CMAKE_BUILD_TYPE.html) in the CMake documentation.

> Do the tests work as expected in a release build? 

they should, but they'll be run with binaries that were created with compiler optimisations enabled.

As always: optimisations are not supposed to affect the correct functioning of a program, but it's not guaranteed.

One other thing: `Release` typically also defines `NDEBUG`, which can influence how `ASSERT` macros and related functionality behaves.

> Is this just about the debugging info

`Release` binaries do indeed not contain any debugging symbols. `RelWithDebInfo` could be used to get optimised binaries *with* symbols. `Debug` contains symbols, but does not optimise.

**Comment by wasowski** [comment]
Yes, the assert thing is important. It is the easiest mechanism for us to create tests that cause failure detectable by generic analysis tools. Right now I am trying to insert some assertions to run b4dc23 but I have not yet figured out how to run it ...

**Comment by gavanderhoorn** [comment]
Moved to new tracker.
